Laravel 8.x Compatibility
cviebrock/eloquent-sluggable pull request #524
Opened 2020-09-07 19:39 UTC by laravel-shift

This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 8.x.

**Before merging**, you need to:

- Checkout the `l8-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

2020-09-07 19:39 UTC, laravel-shift commented
:warning: The latest version of Laravel has a dependency for the `phpunit/phpunit` of `^9.3`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

2020-09-07 19:39 UTC, laravel-shift commented
:alembic: If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/eloquent-sluggable.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "cviebrock/eloquent-sluggable": "dev-l8-compatibility",
    }
}
```

Finally, run: `composer update`

2020-09-08 13:05 UTC, tabacitu requested changes

2020-09-08 13:05 UTC, tabacitu commented on composer.json
> +        "illuminate/support": "^8.0"
Hmmm... personally I would have added Laravel 8 support while still not removing Laravel 7 support, so:
```
"illuminate/database": "^7.0|^8.0",
```

since there should be no breaking changes between them...

What do you think @cviebrock ?

2020-09-08 13:23 UTC, laravel-shift commented on composer.json
> +        "illuminate/support": "^8.0"
This automation analyzes the existing constraints to determine if new constraints should be appended. In this case, since the current version only supports the latest version of Laravel, the automation did the same for Laravel 8.

You, of course, are welcome to append them. This is aimed at providing a starting point to help package authors support the latest version.

2020-09-08 14:37 UTC, tabacitu commented on composer.json
> +        "illuminate/support": "^8.0"
Indeed - it seems like @cviebrock might prefer to do it this way, since that's what he's done so far. I was just voicing my way to do it 😄 I've provided an alternative in #525 with pipes, if he'd rather go that way.

I have to say - I was thoroughly impressed to see the laravel-shift PR, to an open-source repo. This should IMMENSELY help OSS developers add support for new versions of Laravel. Hat's off to you @jasonmccreary - excellent job.

2020-09-08 14:40 UTC, jasonmccreary commented on composer.json
> +        "illuminate/support": "^8.0"
Thanks! Just doing my part to help every stay up-to-date. I know how much it can be for the community at large as more of more applications depend on packages.

2020-09-10 21:32 UTC, cviebrock commented on composer.json
> +        "illuminate/support": "^8.0"
Thanks for this @jasonmccreary ... having a bot update my packages makes my life considerably easier. 😉

2020-09-10 21:34 UTC, cviebrock approved these changes

2020-09-10 21:34 UTC, merged

2020-09-10 21:36 UTC, jasonmccreary commented on composer.json
> +        "illuminate/support": "^8.0"
Exactly what I was going for... Hopefully this provided a good start.